### ISSUE TITLE
Indexing stops for almost all repositories

### ISSUE THREAD

**Issue by valentijnscholten** [mteodori/jira-git-plugin#13]
Hello,

I am noticing that almost for every git repository configured in jira, after a while the indexing stops. The repository is deactivated. I can press Activate to get it working again, but after a while it stops working again.
Probably there are some exceptions during the indexing, I will report what I find in the logs.

Do you want the exceptions grouped into this one issue, or a seperate issue for each type of exception?

Valentijn

**Comment by valentijnscholten** [comment]
```
2014-03-02 20:52:05,462 QuartzScheduler_Worker-0 ERROR ServiceRunner    Git Revision Indexing Service [xiplink.jira.git.GitManagerImpl] Error retrieving changes
 from the repository.
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 4d17c065eceac197654703b41a6d584c93e2ef8e
        at org.eclipse.jgit.storage.file.WindowCursor.open(WindowCursor.java:111)
        at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:228)
        at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:811)
        at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:724)
        at com.xiplink.jira.git.GitManagerImpl.parseCommit(GitManagerImpl.java:151)
        at com.xiplink.jira.git.GitManagerImpl.markUninteresting(GitManagerImpl.java:161)
        at com.xiplink.jira.git.GitManagerImpl.getLogEntries(GitManagerImpl.java:222)
        at com.xiplink.jira.git.revisions.RevisionIndexer.updateBranchIndex(RevisionIndexer.java:268)
        at com.xiplink.jira.git.revisions.RevisionIndexer.updateIndex(RevisionIndexer.java:220)
        at com.xiplink.jira.git.revisions.RevisionIndexer.updateIndex(RevisionIndexer.java:169)
        at com.xiplink.jira.git.revisions.RevisionIndexService.run(RevisionIndexService.java:31)
        at com.atlassian.jira.service.JiraServiceContainerImpl.run(JiraServiceContainerImpl.java:61)
        at com.atlassian.jira.service.ServiceRunner.execute(ServiceRunner.java:48)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:195)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
2014-03-02 20:52:05,480 QuartzScheduler_Worker-0 WARN ServiceRunner    Git Revision Indexing Service [jira.git.revisions.RevisionIndexer] Unable to index repository 'Winkelstraat'
java.lang.NullPointerException
        at com.xiplink.jira.git.GitManagerImpl.getRefId(GitManagerImpl.java:110)
        at com.xiplink.jira.git.revisions.RevisionIndexer.updateBranchIndex(RevisionIndexer.java:250)
        at com.xiplink.jira.git.revisions.RevisionIndexer.updateIndex(RevisionIndexer.java:220)
        at com.xiplink.jira.git.revisions.RevisionIndexer.updateIndex(RevisionIndexer.java:169)
        at com.xiplink.jira.git.revisions.RevisionIndexService.run(RevisionIndexService.java:31)
        at com.atlassian.jira.service.JiraServiceContainerImpl.run(JiraServiceContainerImpl.java:61)
        at com.atlassian.jira.service.ServiceRunner.execute(ServiceRunner.java:48)
        at org.quartz.core.JobRunShell.run(JobRunShell.java:195)
        at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:520)
```

Although this shouldn't happen, maybe just skip the revision that cannot be found?
